### ISSUE TITLE
ValueError conflict with Django treenode

### ISSUE THREAD

**Issue by liamlawless35** [adamghill/django-unicorn#409]
I've tried working this out on my own for ages and I still can't figure it out. So 99% of the time everything works perfectly. After a seemingly random number of clicks, Django will shoot me an error message 

> Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<decorator-gen-25>", line 2, in message
    <source code not available>
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/decorators.py", line 17, in timed
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/__init__.py", line 43, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/__init__.py", line 485, in message
    json_result = _handle_component_request(request, component_request)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/__init__.py", line 331, in _handle_component_request
    return _process_component_request(request, component_request)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/__init__.py", line 93, in _process_component_request
    set_property_from_data(component, property_name, property_value)
  File "<decorator-gen-21>", line 2, in set_property_from_data
    <source code not available>
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/decorators.py", line 17, in timed
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/utils.py", line 62, in set_property_from_data
    set_property_from_data(field, key, key_value)
  File "<decorator-gen-21>", line 2, in set_property_from_data
    <source code not available>
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/decorators.py", line 17, in timed
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_unicorn/views/utils.py", line 90, in set_property_from_data
    setattr(component_or_field, name, value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 215, in __set__
    raise ValueError(
Exception Type: ValueError at /unicorn/message/Chooser
Exception Value: Cannot assign "1": "Node.tn_parent" must be a "Node" instance.

(Node.tn_parent is a Django treenode property)

The kicker? This doesn't affect anything on the user side. The function is executed flawlessly. The only visible problem is on server side where there's a slight bump in performance. I'd prefer to fix it to smooth out said problem.

Apologies in advance if this is the wrong place to talk about this.

**Comment by liamlawless35** [comment]
Ah, one thing. On the user side, the developer console spits a 500 error at me. Again, the site itself still works???

**Comment by adamghill** [comment]
Sometimes data gets serialized incorrectly, but it's frustrating this only happens once in a while. If you can create an example or test that replicates the problem I'd love to look at it.

**Comment by Yethiel** [comment]
I think I have a similar problem where in unicorn:data `user: 1` only sometimes causes this problem but `user: "1"` always causes the same value error.
For me the cause is different though because I'm using a select to choose a user ID.

`Cannot assign "'1'": "Ticket.user" must be a "User" instance.`

**Comment by JohananOppongAmoateng** [comment]
Related to #732?

**Comment by JohananOppongAmoateng** [comment]
#780 merged closing this for the meantime until we can get confirmation this still happens
