### ISSUE TITLE
File download inside django-unicorn

### ISSUE THREAD

**Issue by rjlinuxekoos** [adamghill/django-unicorn#486]
Hi!
I'm trying to download PDF files from the django runserver development server, "python manager.py runserver", inside a django-unicorn application, but I can't download them. Follow the code >
with open(os.path.join("c:/mydirectory/tmp", filename + '.pdf'), 'rb') as f:
                    data = f.read()  

                response = HttpResponse(data, content_type='application/pdf')
                response['Content-Disposition'] = 'attachment; filename="' + filename + '.pdf"'
                
                return response

No error occurs, but accessing from another machine I can't download.
Is there any way to be reproduced?
Thanks!

**Comment by adamghill** [comment]
Where is this code? Is it inside a `Unicorn` component or somewhere else? If you can create a repo that demonstrates the problem I can take a look at it. Thanks!

**Comment by pa-hqt** [comment]
Hello @adamghill,
I think I have a similiar feature request and created a minimal example based on your repository:
https://github.com/pa-hqt/django-unicorn/tree/example/file-download
Run server and visit http://localhost:8000/file-response

I would like to be able to provide a dynamically created file, when user clicks on a download button. To create the file, I need data that exist within the unicorn component.

My stupid approach was to call an action method that returns a FileResponse (like you can return HttpResponseRedirect), but unfortunately that crashes with following exception:

```
Type is not JSON serializable: FileResponse
TypeError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "\django-unicorn\django_unicorn\views\objects.py", line 157, in get_data
    serialized_value = loads(dumps(self.value))
  File "\django-unicorn\django_unicorn\serializer.py", line 414, in dumps
    serialized_data = orjson.dumps(data, default=_json_serializer)
TypeError: Type is not JSON serializable: FileResponse
```

If there is another possible approach, I would be thankful to get advice. Maybe I can access the UnicornView instance from the outer/wrapping django view?

**Comment by adamghill** [comment]
I think your inclination to return `FileResponse` makes sense -- it feels intuitive to me at least. But, I'll need to build something into `Unicorn` to support it. I explicitly handle the redirect response, convert it into JSON, and then do specific things client-side in JavaScript so it all feels seamless.

How big is the file? Is it reasonable for `Unicorn` to store it in a cache server-side? Or in a temporary directory?

I think one potential workflow would be:
1. Component action creates the file
2. Component returns FileResonse
3. Unicorn takes file bytes, stores in temp directory with a unique identifier, passes that unique identifier back to the client in JSON
4. JS makes a call the server with unique identifier
5. Server responds with actual file read from temporary file

**Comment by pa-hqt** [comment]
In my case it will be an Excel file with a size of 200-600KB, but I think larger files of 10MB or so should be supported too. In general the temporary directory should be 

Your workflow sounds sensible. Some comments that come to my mind:
- By comsuming the FileResponse (to write it to temp. file), sending the identifier and trigger a second request to consume the file again, you create an extra request roundtrip. But you achieve that the file size is nearly irrelevant.
- For small files it might be a solution to return the encoded bytes in the first response, but that has other disadvantages:
  - File streaming is not possible, which limits the reasonable file size that can be handled
  - File handling in JS might be another difficulty

Thank you for considering this for your nice project
