### ISSUE TITLE
Bug: unicorn:poll throwing error

### ISSUE THREAD

**Issue by JohnyCarrot** [adamghill/django-unicorn#629]
Greetings.

Im using 0.57.1 (should be newest) version of django unicorn. When i use unicorn:poll in unicorn template or poll with seconds (exactly like in documentation, using same code etc) i got this error:

```
AttributeError: 'str' object has no attribute 'year'
[14/Nov/2023 13:40:40] "POST /unicorn/message/navbar HTTP/1.1" 500 20941
Internal Server Error: /unicorn/message/navbar
Traceback (most recent call last):
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<decorator-gen-30>", line 2, in message
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\views\__init__.py", line 46, in wrapped_view
    return view_func(*args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\views\__init__.py", line 522, in message
    json_result = _handle_component_request(request, component_request)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\views\__init__.py", line 375, in _handle_component_request
    return _process_component_request(request, component_request)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\views\__init__.py", line 102, in _process_component_request
    set_property_from_data(component, property_name, property_value)
  File "<decorator-gen-26>", line 2, in set_property_from_data
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\views\utils.py", line 82, in set_property_from_data
    component_or_field._set_property(name, value, call_updating_method=True, call_updated_method=False)
  File "<decorator-gen-20>", line 2, in _set_property
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\components\unicorn_view.py", line 618, in _set_property
    form = self._get_form(data)
  File "<decorator-gen-14>", line 2, in _get_form
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django_unicorn\decorators.py", line 27, in timed
    arguments = f"{args}, "
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\db\models\query.py", line 373, in __repr__
    return "<%s %r>" % (self.__class__.__name__, data)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\db\models\base.py", line 586, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\notifications\base\models.py", line 250, in __str__
    'timesince': self.timesince()
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\notifications\base\models.py", line 266, in timesince
    return timesince_(self.timestamp, now)
  File "L:\GITHUB\mapa-chranenych-oblasti-sr\venv\lib\site-packages\django\utils\timesince.py", line 53, in timesince
    d = datetime.datetime(d.year, d.month, d.day)
AttributeError: 'str' object has no attribute 'year'

```
Python version: 3.9.7

**Comment by wallem89** [comment]
Are you sure this is related to ```unicorn:poll```? Because I see a lot of errors but it doesn't look like it is related. Does your page work without ```unicorn:poll```? And can you paste your unicorn template and components here?

**Comment by JohnyCarrot** [comment]
Oh, i figured it out already. The issue was another library that just seems to not work with unicorn, i used some other. Thanks in advance
